import { GeoData, Product } from "./types";

export const PRODUCTS = {
  starter: {
    id: "starter" as const,
    name: "Budget Starter",
    nameHi: "बजट स्टार्टर",
    tagline: "Start with clarity. Stop the salary leak. Build the habit.",
    taglineHi: "स्पष्टता से शुरू करें। सैलरी की चुंगी रोकें। आदत बनाएं।",
    purchaseLink: "https://superprofile.bio/vp/orgatreeker",
    wistiaMediaId: "q2fgrmv8ze",
    outcomes: [
      "You know where every rupee goes — every month, automatically",
      "You have stopped the salary leak",
      "You are saving ₹2,000–₹5,000 more every month",
      "Budgeting takes you 10 minutes a month — not an hour",
      "You feel in control for the first time",
    ],
    outcomesHi: [
      "आप जानते हैं हर रुपया कहाँ जाता है — हर महीने, ऑटोमैटिकली",
      "आपने सैलरी की चुंगी रोक दी है",
      "आप हर महीने ₹2,000–₹5,000 ज़्यादा बचा रहे हैं",
      "बजटिंग में अब सिर्फ 10 मिनट लगते हैं — एक घंटा नहीं",
      "पहली बार आप कंट्रोल में महसूस कर रहे हैं",
    ],
    features: [
      "Monthly expense tracker (1 main tab)",
      "50/30/20 auto-calculator",
      "Basic savings tracker",
      "Bill payment calendar",
      "Video tutorial walkthrough",
    ],
    featuresHi: [
      "मंथली खर्च ट्रैकर (1 मेन टैब)",
      "50/30/20 ऑटो-कैलकुलेटर",
      "बेसिक सेविंग्स ट्रैकर",
      "बिल पेमेंट कैलेंडर",
      "वीडियो ट्यूटोरियल वॉकथ्रू",
    ],
  },
  complete: {
    id: "complete" as const,
    name: "Budget Master",
    nameHi: "बजट मास्टर",
    tagline: "A full financial operating system. Built for serious goals.",
    taglineHi: "एक पूरा फाइनेंशियल ऑपरेटिंग सिस्टम। गंभीर लक्ष्यों के लिए।",
    purchaseLink: "https://superprofile.bio/vp/organise-your-money--beautifully",
    wistiaMediaId: "vzvp3kwo4r",
    outcomes: [
      "Complete visibility — income, expenses, savings, investments, net worth — all in one place",
      "SIPs are running and tracked automatically",
      "EMIs are managed with a clear payoff timeline",
      "Emergency fund is being built toward a 3-month target",
      "You know your net worth and it is growing",
      "1 personal setup session with Gopu to make sure everything is right",
    ],
    outcomesHi: [
      "पूरी विज़िबिलिटी — इनकम, खर्चे, सेविंग्स, इन्वेस्टमेंट्स, नेट वर्थ — सब एक जगह",
      "SIPs चल रहे हैं और ऑटोमैटिकली ट्रैक हो रहे हैं",
      "EMIs मैनेज हैं एक क्लियर पेऑफ टाइमलाइन के साथ",
      "इमरजेंसी फंड 3 महीने के टारगेट की तरफ बन रहा है",
      "आप अपनी नेट वर्थ जानते हैं और वो बढ़ रही है",
      "Gopu के साथ 1 पर्सनल सेटअप सेशन ताकि सब सही हो",
    ],
    features: [
      "Everything in Budget Starter PLUS:",
      "SIP & investment tracker",
      "EMI & debt planner",
      "Savings goal tracker (multiple goals)",
      "Annual dashboard",
      "Bank account tracker",
      "Net worth tracker",
      "Sinking funds tracker",
      "Full video tutorial (advanced)",
      "1 setup session with Gopu (post-purchase)",
    ],
    featuresHi: [
      "बजट स्टार्टर में सब कुछ और साथ में:",
      "SIP और इन्वेस्टमेंट ट्रैकर",
      "EMI और डेट प्लानर",
      "सेविंग्स गोल ट्रैकर (मल्टीपल गोल्स)",
      "एनुअल डैशबोर्ड",
      "बैंक अकाउंट ट्रैकर",
      "नेट वर्थ ट्रैकर",
      "सिंकिंग फंड्स ट्रैकर",
      "फुल वीडियो ट्यूटोरियल (एडवांस्ड)",
      "Gopu के साथ 1 सेटअप सेशन (खरीदने के बाद)",
    ],
  },
};

export const GEO_PRICING: Record<string, Omit<GeoData, "country" | "countryCode">> = {
  IN: {
    currency: "INR",
    currencySymbol: "₹",
    starterPrice: 499,
    completePrice: 1599,
    salaryPlaceholder: "e.g. ₹50,000",
  },
  US: {
    currency: "USD",
    currencySymbol: "$",
    starterPrice: 6,
    completePrice: 19,
    salaryPlaceholder: "e.g. $5,000",
  },
  GB: {
    currency: "GBP",
    currencySymbol: "£",
    starterPrice: 5,
    completePrice: 15,
    salaryPlaceholder: "e.g. £4,000",
  },
  CA: {
    currency: "CAD",
    currencySymbol: "C$",
    starterPrice: 8,
    completePrice: 26,
    salaryPlaceholder: "e.g. C$5,500",
  },
  AU: {
    currency: "AUD",
    currencySymbol: "A$",
    starterPrice: 9,
    completePrice: 29,
    salaryPlaceholder: "e.g. A$6,000",
  },
  SG: {
    currency: "SGD",
    currencySymbol: "S$",
    starterPrice: 8,
    completePrice: 25,
    salaryPlaceholder: "e.g. S$5,000",
  },
  AE: {
    currency: "AED",
    currencySymbol: "AED",
    starterPrice: 22,
    completePrice: 70,
    salaryPlaceholder: "e.g. AED 15,000",
  },
  NG: {
    currency: "NGN",
    currencySymbol: "₦",
    starterPrice: 3700,
    completePrice: 11900,
    salaryPlaceholder: "e.g. ₦200,000",
  },
  DE: {
    currency: "EUR",
    currencySymbol: "€",
    starterPrice: 6,
    completePrice: 19,
    salaryPlaceholder: "e.g. €4,000",
  },
  FR: {
    currency: "EUR",
    currencySymbol: "€",
    starterPrice: 6,
    completePrice: 19,
    salaryPlaceholder: "e.g. €4,000",
  },
  DEFAULT: {
    currency: "USD",
    currencySymbol: "$",
    starterPrice: 6,
    completePrice: 19,
    salaryPlaceholder: "e.g. $5,000",
  },
};

export const QUIZ_QUESTIONS = {
  en: [
    {
      id: 1,
      question: "What is your monthly take-home salary?",
      options: [
        { id: 1, text: "Under ₹25,000", score: 1 },
        { id: 2, text: "₹25,000 – ₹50,000", score: 1 },
        { id: 3, text: "₹50,000 – ₹80,000", score: 0 },
        { id: 4, text: "₹80,000 – ₹1,50,000", score: 2 },
        { id: 5, text: "More than ₹1,50,000", score: 2 },
      ],
    },
    {
      id: 2,
      question: "Which of these describes your money situation right now?",
      options: [
        { id: 1, text: "My salary runs out before month end — I don't know where it goes", score: 0 },
        { id: 2, text: "I track roughly, but I still feel out of control", score: 0 },
        { id: 3, text: "I save some money but I want to do more with it", score: 2 },
        { id: 4, text: "I earn well and I want a complete financial system", score: 2 },
      ],
    },
    {
      id: 3,
      question: "What is your biggest financial goal right now?",
      options: [
        { id: 1, text: "Stop my salary from running out every month", score: 0 },
        { id: 2, text: "Save ₹3,000 – ₹10,000 more every month", score: 0 },
        { id: 3, text: "Build an emergency fund", score: 1 },
        { id: 4, text: "Start or grow my investments (SIPs, mutual funds)", score: 2 },
        { id: 5, text: "Pay off my loans and EMIs faster", score: 2 },
        { id: 6, text: "Build real long-term wealth", score: 2 },
      ],
    },
    {
      id: 4,
      question: "Have you tried budgeting before?",
      options: [
        { id: 1, text: "Never — this is my first time", score: 0 },
        { id: 2, text: "Yes — apps like Walnut, Moneyfy, etc. (didn't stick)", score: 0 },
        { id: 3, text: "Yes — my own spreadsheet (works sometimes)", score: 1 },
        { id: 4, text: "Yes — I have a system but it is not complete enough", score: 2 },
      ],
    },
    {
      id: 5,
      question: "Which of these financial tools have you used or heard of?",
      options: [
        { id: 1, text: "None of these — I am just starting out", score: 0 },
        { id: 2, text: "SIP / Mutual Funds (but I have not started yet)", score: 0 },
        { id: 3, text: "I invest in SIPs already", score: 2 },
        { id: 4, text: "I manage EMIs, investments, and multiple savings goals", score: 2 },
      ],
    },
    {
      id: 6,
      question: "Which language do you prefer?",
      options: [
        { id: 1, text: "English", score: 0 },
        { id: 2, text: "हिंदी (Hindi)", score: 0 },
      ],
    },
  ],
  hi: [
    {
      id: 1,
      question: "आपकी मंथली टेक-होम सैलरी क्या है?",
      options: [
        { id: 1, text: "₹25,000 से कम", score: 1 },
        { id: 2, text: "₹25,000 – ₹50,000", score: 1 },
        { id: 3, text: "₹50,000 – ₹80,000", score: 0 },
        { id: 4, text: "₹80,000 – ₹1,50,000", score: 2 },
        { id: 5, text: "₹1,50,000 से ज़्यादा", score: 2 },
      ],
    },
    {
      id: 2,
      question: "इनमें से कौन सा आपकी पैसों की स्थिति बताता है?",
      options: [
        { id: 1, text: "महीने खत्म होने से पहले सैलरी खत्म हो जाती है — पता नहीं कहाँ जाती है", score: 0 },
        { id: 2, text: "कुछ-कुछ ट्रैक करता हूँ, पर फिर भी कंट्रोल में नहीं लगता", score: 0 },
        { id: 3, text: "कुछ पैसे बचाता हूँ पर और करना चाहता हूँ", score: 2 },
        { id: 4, text: "अच्छा कमाता हूँ और एक पूरा फाइनेंशियल सिस्टम चाहिए", score: 2 },
      ],
    },
    {
      id: 3,
      question: "अभी आपका सबसे बड़ा फाइनेंशियल गोल क्या है?",
      options: [
        { id: 1, text: "हर महीने सैलरी खत्म होना रोकना", score: 0 },
        { id: 2, text: "हर महीने ₹3,000 – ₹10,000 ज़्यादा बचाना", score: 0 },
        { id: 3, text: "इमरजेंसी फंड बनाना", score: 1 },
        { id: 4, text: "इन्वेस्टमेंट शुरू करना या बढ़ाना (SIPs, म्यूचुअल फंड्स)", score: 2 },
        { id: 5, text: "लोन और EMIs जल्दी चुकाना", score: 2 },
        { id: 6, text: "लॉन्ग-टर्म वेल्थ बनाना", score: 2 },
      ],
    },
    {
      id: 4,
      question: "क्या आपने पहले बजटिंग ट्राई की है?",
      options: [
        { id: 1, text: "कभी नहीं — पहली बार है", score: 0 },
        { id: 2, text: "हाँ — Walnut, Moneyfy जैसे apps (टिके नहीं)", score: 0 },
        { id: 3, text: "हाँ — खुद की स्प्रेडशीट (कभी-कभी काम करती है)", score: 1 },
        { id: 4, text: "हाँ — एक सिस्टम है पर पूरा नहीं है", score: 2 },
      ],
    },
    {
      id: 5,
      question: "इनमें से कौन से फाइनेंशियल टूल्स आपने यूज़ किए या सुने हैं?",
      options: [
        { id: 1, text: "इनमें से कोई नहीं — अभी शुरू कर रहा हूँ", score: 0 },
        { id: 2, text: "SIP / म्यूचुअल फंड्स (पर शुरू नहीं किया)", score: 0 },
        { id: 3, text: "SIPs में इन्वेस्ट करता हूँ", score: 2 },
        { id: 4, text: "EMIs, इन्वेस्टमेंट्स, और मल्टीपल सेविंग्स गोल्स मैनेज करता हूँ", score: 2 },
      ],
    },
    {
      id: 6,
      question: "आप कौन सी भाषा पसंद करते हैं?",
      options: [
        { id: 1, text: "English", score: 0 },
        { id: 2, text: "हिंदी (Hindi)", score: 0 },
      ],
    },
  ],
};
